name       : arc-icon-theme
version    : 20160605
release    : 5
source     :
    - https://solus-project.com/sources/arc-icon-theme-20160605.tar.xz : 264115ad1b3d10ed0264fd745052b59c3f0ce1f1dd4bc42807692dee116f537d
license    : GPL-3.0
component  : desktop.theme
summary    : The beautifulu Arc Icon Theme
description: |
    The Arc Icon Theme, part of the beautiful Arc Theme Suite
rundeps    :
    - hicolor-icon-theme
    - moka-icon-theme
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
