name       : arc-icon-theme
version    : 20160605
release    : 1
source     :
    - https://github.com/horst3180/arc-icon-theme/archive/20160605.tar.gz : 57d4f6ee79a9b541524d8f76b40e06ba361654efd0b9c513cf940209e204eeda
license    : GPL-3.0
component  : desktop.theme
summary    : The beautifulu Arc Icon Theme
description: |
    The Arc Icon Theme, part of the beautiful Arc Theme Suite
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
